### ISSUE TITLE
Old screenshot in docs

### ISSUE THREAD

**Issue by Kaixhin** [facebook/UETorch#1]
The [screenshot](https://github.com/facebook/UETorch/blob/master/Resources/Screenshots/torchplugin_module.png) for step 5 in [Getting Started with UETorch](https://github.com/facebook/UETorch#getting-started-with-uetorch) has `unrealtorch_example` displayed in the Main Module input - it should now be `uetorch_example` (matching with the text).

**Comment by adamlerer** [comment]
Thanks Kaixhin, you're right. I'm out of town so I won't have access to UE until Monday, but I fixed it in powerpoint in the meantime.

**Comment by adamlerer** [comment]
Fixed in c4f37a6228b2c427b194beffe85ee092b230be70.

**Comment by soumith** [comment]
our codemod needs to work with image OCR too :-/
