### ISSUE TITLE
Does it support latest version of Unreal Engine?

### ISSUE THREAD

**Issue by GentleZhu** [facebook/UETorch#19]
I try to manually set the git patch in Unreal Engine 4.12. The directory structure is different from 4.8 and once add torch plugin, the editor crashes.

**Comment by marioyc** [comment]
No, some of the files' locations changed, and there was a bug in ScriptGeneratorPlugin starting from 4.9 which  you could patch with the first part of this diff: http://puu.sh/kUA6O/7b1e6eed6b.diff
I had already done most of the changes necessary for 4.10, so I could add that patch if you need it

**Comment by marioyc** [comment]
Found it, it should go like this for 4.10: http://pastie.org/10885471
It is missing the changes to ScriptGeneratorPlugin from the other diff

**Comment by GentleZhu** [comment]
Thanks!  I will try install UETorch on 4.10 :)

**Comment by GentleZhu** [comment]
I've patched both. But do you have the issues redefinition of 'Character_SetReplicateMovement' in Character.script.h. It seems LuaScriptCodeGenerator.cpp generates two identical function name with different body.
