### ISSUE TITLE
Function CaptureScreenshot crashes in UE4.10

### ISSUE THREAD

**Issue by GentleZhu** [facebook/UETorch#20]
I tried to install UETorch on UE4.10. Everything is fine except editor will crash once uetorch.Screen() is called(Signal 11 caught, probably access wrong memory address). Does it happen in your test?

**Comment by adamlerer** [comment]
I heard about someone else having this problem because they were using two
TorchComponents instead of one. Are you doing that?

**Comment by GentleZhu** [comment]
Sorry, what do you mean by saying two TorchComponents, embeded in blueprints or during installing process?

**Comment by GentleZhu** [comment]
![demo](https://cloud.githubusercontent.com/assets/5558201/16290643/2f0d7164-38cd-11e6-8b02-85dca1843ed3.png)
I tested the demo gave out on README:
1. Add torch plugin on FirstPersonCharacter
2. Edit event graph, replace 'trepl()' with uetorch.Screen(). In UE4.8 it screenshots once pressed the key, but crashes in UE4.10.
3. It crashes when accessing utlib.CaptureScreenshot()

**Comment by adamlerer** [comment]
Oh, I haven't tried 4.10 so I don't know anything specific to it. Do you know how to debug in gdb? @marioyc have you tried screenshot in 4.10?


Get Outlook for Android






On Wed, Jun 22, 2016 at 11:08 PM -0400, "Bran" <notifications@github.com> wrote:














I tested the demo gave out on README:

1. Add torch plugin on FirstPersonCharacter

2. Edit event graph, replace 'trepl()' with uetorch.Screen(). In UE4.8 it screenshots once pressed the key, but crashes in UE4.10.

3. It crashes when accessing utlib.CaptureScreenshot()

**Comment by marioyc** [comment]
Are you getting some error before it crashes?

**Comment by GentleZhu** [comment]
Hi Mario,

The only error I got is Signal 11 caught or *** Error in `./Engine/Binaries/Linux/UE4Editor': malloc(): memory corruption: 0x000000001562aaf0 ***. As I reported before, there is redefinition of 'Character_SetReplicateMovement' in Character.script.h. I just rename one function and compile successfully. I'm not sure if it will cause memory corruption about screenshots.
![bash_log](https://cloud.githubusercontent.com/assets/5558201/16316255/b11f4d68-3953-11e6-9b3a-fcf4478cf826.png)
