### ISSUE TITLE
fatal error: 'lua.h'

### ISSUE THREAD

**Issue by vladfi1** [facebook/UETorch#21]
I get this when trying to `make UE4Editor`. I have this file at `~/torch/exe/luajit-rocks/lua-5.2/src/lua.h`.

**Comment by adamlerer** [comment]
Hi @vladfi1 , did Setup.sh run properly? Or did you get an error message that says

```
Couldn't find lua.h relative to lua. Did you forget to install torch and run torch-activate?
```

**Comment by vladfi1** [comment]
It did run properly, saying `SUCCESS` at the end.

**Comment by vladfi1** [comment]
Ah, I see now you meant `Engine/Plugins/UETorch/Setup.sh`, not the one in Unreal's root directory. That one indeed failed to find lua.h, which I fixed by reinstalling torch.

I'm now having a different issue, which seems to match this [description](https://answers.unrealengine.com/questions/258959/ue4editor-linux-crash.html) - it appears that Unreal 4.8 doesn't run on Ubuntu 15.10. Are you guys using 14.04?

**Comment by adamlerer** [comment]
Yes, that's correct. Please refer to the wiki on running unreal engine 4 on
Linux, linked in the UETorch Readme.
