### ISSUE TITLE
Similar problem: torch plugin don't fire in packaged game

### ISSUE THREAD

**Issue by GentleZhu** [facebook/UETorch#23]
Hi,

I've looked at your discussion below. I have a similar problem that everything is correct but UETorch don't fire. Once I tried to intrigue the callTorchFunction, it shows LogScript:Warning: Accessed None 'TorchPlugin'. And I tried with add lua library folder but doesn't work. I wonder if it is the same issue reported before.

**Comment by adamlerer** [comment]
You are trying to call Lua from Blueprints using callTorchFunction() but it fails with "Accessed None 'TorchPlugin'?

You should attach a picture of the blueprint. Also check that TorchPlugin is enabled within your game, and make sure that UETorch/Setup.sh succeeded when you ran it.

**Comment by adamlerer** [comment]
Hi @GentleZhu . I just upgrading UETorch to use the latest version of Unreal Engine (4.13), and during that upgrade I fixed a mistake that may have caused UETorch to not be included in packaged games (https://github.com/facebook/UETorch/commit/4e74e00adfdbcff97db09d91dfb68e98e30a4790#diff-251d21f95faf551d988003883e0a6e3fR15). Can you install the latest version (either start from scratch or make sure Unreal Engine is not still patched on 4.8), and see if it works now?
