### ISSUE TITLE
Scripts for the paper: "Learning Physical Intuition of Block Towers by Example"

### ISSUE THREAD

**Issue by memimo** [facebook/UETorch#25]
Would be any chance that you will release the scripts for generating the blocks tower dataset?

**Comment by adamlerer** [comment]
Hi @memimo, the blocks tower dataset was largely generated via UE blueprints before a lot of the object manipulation functions were available in UETorch, so it is hard to share unless you want the .uasset binaries (this difficulty of sharing code via blueprints is a big reason for UETorch).

I can, however, make available the full dataset of "Learning Physical Intuition of Block Towers by Example" if you'd like. Also, it should be quite easy to generate a similar environment in UETorch using the `setActorLocation()`, `setActorMaterial()`, etc. functions.

If you're just looking for a good example for data generation in UETorch, there is `Scripts/uetorch_example.lua`, and I think @marioyc was planning to release something more complex soon. If not, I can hack together something similar to the blocks generation in UETorch.

**Comment by marioyc** [comment]
Yes, it isn't finished yet, but you can take a look at: https://github.com/bootphon/NaivePhysics

**Comment by memimo** [comment]
Thanks @adamlerer Actually if you could release the datasets from the paper that would be ideal.  As I am working on a similar problem and would be great if could have a baseline on your dataset as well. Thanks in advance!
And thanks @marioyc for sharing the scripts, this is very helpful!

**Comment by adamlerer** [comment]
Hi @memimo I've put the datasets on Dropbox for now, you can access them at https://www.dropbox.com/sh/9n00jyzo0m2slxe/AAChn5uB5g4HHu2mZxbapgzsa?dl=0

Don't hesitate to reach out if you have more questions or need some other data.

**Comment by memimo** [comment]
Thanks a lot, much appreciated!

**Comment by iffsid** [comment]
Thanks @adamlerer and @marioyc for the links! Unfortunately though, dropbox doesn't allow me to either download the dataset directly ("The zipfile is too large") or add it to my Dropbox ("This folder has too many files to add to your Dropbox."). I suspect the latter message is because I don't have a dropbox premium account? Are there any other sources for the data I could use? Maybe an ftp server?  -iffsid

**Comment by memimo** [comment]
@iffsid Downloading the files individually worked for me.

**Comment by iffsid** [comment]
doh! thanks. :-)

**Comment by iliTheFallen** [comment]
Hello Mr. Lerer;
Are you planning to publish your synthetic dataset or data generating script anytime soon? We would like to make a one-to-one comparison with your results. My another question is that you'd uploaded dataset for real-case; but there is no metadata specifying whether an individual sample is the one in which tower falls or not. Do you have labels for the real-dataset?

**Comment by adamlerer** [comment]
Hi,

The synthetic dataset was in that dropbox folder but I removed it because it was quite large; I can add it back for you if you'd like to use it.

The metadata for each dataset is included in the top-level directory of the tar archive.

**Comment by iliTheFallen** [comment]
Yeah that would be great @adamlerer . I will let you know as soon as we download it so that you can make room on your dropbox account. We have been trying to make good use of what @marioyc mentioned; but it seems that we will not be able to catch up with some conferences on time if we use it. 

Oh I see. I will check out the metadata again. Maybe I missed out something; because I couldn't find any information regarding the label indicating whether a given tower falls or not.

**Comment by adamlerer** [comment]
@iliTheFallen It's on Dropbox now. Good luck! What did @marioyc mention? Btw no we will not publish the data generating script because unfortunately it was built with a very old version of UETorch + Blueprints and would be hard to make usable for others.

**Comment by iliTheFallen** [comment]
Thanks @adamlerer for the input data. We downloaded it; but we are planning to use an RNN-based architecture and we need the frame-sequence. It seems the frames located in images folder are random images from different configurations, right? Thanks for the masks which are ground truths we suppose? My question is: Do you have the frame-sequences that corresponds to these masks? If you have them and share them with us; we would be really glad.

Oh, @marioyc had mentioned that they distribute a library called ["intphys"](https://github.com/bootphon/intphys). However, it seems we need some time to learn how to use it.

**Comment by iliTheFallen** [comment]
@adamlerer , would you mind sharing the time-series for synthetic input data? I couldn't find it in the synthetic folder you uploaded. It seems there are only time-series for masks (ground-truths). We'd be grateful if you could upload them too for we'll be using an RNN-based approach.

**Comment by adamlerer** [comment]
Hi @iliTheFallen That data is huge (100s of GB) so we'd have to figure out a different way to transfer it, and to be honest I'm not sure we still have it.

**Comment by iliTheFallen** [comment]
Oh I see @adamlerer . It is ok. Then we'll test our proposed RNN architecture on attention/saliency data first. If you can find a better way to share your dataset, I'd love to hear that from you. Thank you for helping us so far.

**Comment by balakg** [comment]
@adamlerer was wondering if there was a way to get the synthetic blocks dataset. Thanks for making the real examples available.
