### ISSUE TITLE
Couldn't find lua.h relative to lua.

### ISSUE THREAD

**Issue by floringogianu** [facebook/UETorch#27]
When executing the `UETorch` installation script `./Engine/Plugins/UETorch/Setup.sh` I get this:

```
=== Setting up Lua... === 
Couldn't find lua.h relative to lua. Did you forget to install torch and run torch-activate?
```

I am on Ubuntu 16.04 and I have torch installed, activated and working properly. The `lua` command points to the runtime installed by the system (most likely not the one used by `torch`). Suggestions?

**Comment by adamlerer** [comment]
Hi Florian. If you ran `source torch-distro/install/bin/torch-activate`, then `which lua` should point at the lua in the torch distro. Just look inside of `torch-activate`, it puts it at the beginning of your path:
```
export PATH=/home/alerer/local/git/torch-distro/install/bin:$PATH
```
