### ISSUE TITLE
depth map and segmentation of 3D character with skeleton have a problem

### ISSUE THREAD

**Issue by donghyunyoo** [facebook/UETorch#38]
Hi

I tried to make depth map and segmentation of 3D character model.
The model has a skeleton and animation that is generated by adobe Fuse and Mixamo. 
When I got depth map and segmentation, its depth map and segmentation look like its skeleton not mesh.
![uetorch_screenshot](https://cloud.githubusercontent.com/assets/23063017/21339430/22c99f82-c64d-11e6-9fec-1ee874cf18e8.png)
![uetorch_segmentation](https://cloud.githubusercontent.com/assets/23063017/21339431/26ac0ea0-c64d-11e6-9755-323ff7d3bf91.png)

How can I fix this?

**Comment by adamlerer** [comment]
Hi @donghyunyoo , looks like you're pretty close. I think this might just be an artifact of the image scaling. Can you send me the Lua code you use to generate this depth map?

I'm guessing the values in the depth map are in the wrong range for an image... can you add this print and see what it says?

```
print(img:min(), img:max())
```

**Comment by donghyunyoo** [comment]
Oh. The image was segmentation image. not depth map.
Depth map looks like this. 
My problem is the character looks like skeleton. 
Sorry for confusing you
![uetorch_screenshot_105](https://cloud.githubusercontent.com/assets/23063017/21359119/2a3efaf8-c6a9-11e6-8b08-097d5f0129b6.png)

![uetorch_depthmap_105](https://cloud.githubusercontent.com/assets/23063017/21359091/fdc6d32e-c6a8-11e6-867d-dc8773553c98.png)

**Comment by adamlerer** [comment]
Oh, I see. Sorry, this I don't know much about. Here's my guess: The UETorch functions capture these images by doing a "line trace", which basically does raytracing at each image pixel to see what it intersects. Maybe only the skeleton is visible on this channel. Playing around with these lines may help:

https://github.com/facebook/UETorch/blob/master/Source/UETorch/Private/UETorch.cpp#L693
https://github.com/facebook/UETorch/blob/master/Source/UETorch/Private/UETorch.cpp#L697

or you can find the component on your Actor that displays the "skin" and try to set it to be visible on this channel (?) but you'd have to experiment. The Unreal Engine message boards could help too.

Good luck!
