### ISSUE TITLE
UE4 patch failed

### ISSUE THREAD

**Issue by mrkulk** [facebook/UETorch#4]
I am on Ubuntu 14.04.3 LTS and I installed torch from the latest main branch. I am having problems with 'Engine/Plugins/UETorch/Setup.sh'. The error message is pasted below. I would appreciate any pointers

D	Engine/Source/ThirdParty/zlib/zlib-1.2.5/build/zlib-1.2.5.tar.gz
Already on '4.8'
Your branch is up-to-date with 'origin/4.8'.
Checking dependencies (excluding Win32, Win64, Mac, HTML5, Android)...
Result: 0
=== Patching UE4 ===
error: patch failed: Engine/Source/Runtime/Engine/Classes/Engine/World.h:928
error: Engine/Source/Runtime/Engine/Classes/Engine/World.h: patch does not apply
error: patch failed: Engine/Source/Runtime/Engine/Private/Components/PrimitiveComponent.cpp:1425
error: Engine/Source/Runtime/Engine/Private/Components/PrimitiveComponent.cpp: patch does not apply
error: patch failed: Engine/Source/Runtime/Engine/Private/LevelTick.cpp:1112
error: Engine/Source/Runtime/Engine/Private/LevelTick.cpp: patch does not apply
error: patch failed: Engine/Source/Runtime/Engine/Private/World.cpp:123
error: Engine/Source/Runtime/Engine/Private/World.cpp: patch does not apply
error: patch failed: Engine/Source/Runtime/Linux/ALAudio/Private/ALAudioDevice.cpp:84
error: Engine/Source/Runtime/Linux/ALAudio/Private/ALAudioDevice.cpp: patch does not apply
error: patch failed: Engine/Source/Runtime/Core/Private/Linux/LinuxPlatformProcess.cpp:16
error: Engine/Source/Runtime/Core/Private/Linux/LinuxPlatformProcess.cpp: patch does not apply
error: patch failed: Engine/Plugins/ScriptPlugin/Source/ScriptPlugin/Private/ScriptPlugin.cpp:16
error: Engine/Plugins/ScriptPlugin/Source/ScriptPlugin/Private/ScriptPlugin.cpp: patch does not apply
error: patch failed: Engine/Plugins/ScriptPlugin/Source/ScriptPlugin/Private/LuaIntegration.h:13
error: Engine/Plugins/ScriptPlugin/Source/ScriptPlugin/Private/LuaIntegration.h: patch does not apply
error: patch failed: Engine/Plugins/ScriptGeneratorPlugin/Source/ScriptGeneratorPlugin/Private/ScriptGeneratorPlugin.cpp:97
error: Engine/Plugins/ScriptGeneratorPlugin/Source/ScriptGeneratorPlugin/Private/ScriptGeneratorPlugin.cpp: patch does not apply
error: patch failed: Engine/Plugins/ScriptGeneratorPlugin/Source/ScriptGeneratorPlugin/ScriptGeneratorPlugin.Build.cs:48
error: Engine/Plugins/ScriptGeneratorPlugin/Source/ScriptGeneratorPlugin/ScriptGeneratorPlugin.Build.cs: patch does not apply
error: patch failed: Engine/Plugins/ScriptPlugin/Source/ScriptPlugin/ScriptPlugin.Build.cs:29
error: Engine/Plugins/ScriptPlugin/Source/ScriptPlugin/ScriptPlugin.Build.cs: patch does not apply
=== Setting up Lua... ===

**Comment by adamlerer** [comment]
@mrkulk the Setup.sh script is not idempotent; did you apply it twice? If you do "git status" from UnrealEngine (not UETorch), are there a bunch of modified files e.g. World.cpp? If so, then the patch already got applied.

I'll see if I can modify Setup.sh to be idempotent.

**Comment by adamlerer** [comment]
@mrkulk I modified Setup.sh to commit the changes into a new 4.8-UETorch branch, so it can now be idempotent. Let me know if that clears up your troubles, and thanks for the feedback.

https://github.com/facebook/UETorch/commit/9015e106749c3674c062646c16b00a2a1e349d6c

**Comment by mrkulk** [comment]
@adamlerer : thanks! it works
