### ISSUE TITLE
Taking screenshots at high rate crashes the editor

### ISSUE THREAD

**Issue by itaicaspi** [facebook/UETorch#8]
Taking more than one screenshot per second through the torch binding crashes the editor with the following stack trace:
[stack trace image](https://drive.google.com/open?id=0B-J8617SXlPqUjVDQTRNTG5LOFE)

I tried both in high resolution and low resolution and get the same error.
I actually need ~5 screenshots per second. How can I achieve this?

**Comment by adamlerer** [comment]
I've taken >1 screenshot per second and it worked fine. Can you run the editor in gdb and see if you can isolate the segfault there?

Under 'Play Options' you might also try "Run in a standalone process"; maybe it's something with running it in the editor.

**Comment by itaicaspi** [comment]
Thanks for the reply. Running in a standalone process solved the crashes.
