### ISSUE TITLE
 undefined symbol: lua_newstate error when trying to add Torch Script Plugin

### ISSUE THREAD

**Issue by suryabhupa** [facebook/UETorch#9]
When I get to the step in the tutorial where we have to add in the Torch tutorial, but the following error happens and UnrealEngine simply exits:

[2016.04.27-02.48.57:724][  0]LogContentStreaming: Texture pool size is 0.000000MB
[2016.04.27-02.48.57:880][  0]LogContentStreaming: Texture pool size now 1000 MB
[2016.04.27-02.48.58:973][  8]LogAssetRegistry: Asset discovery search completed in 20.9050 seconds
/home/surya/UnrealEngine/Engine/Binaries/Linux/UE4Editor: symbol lookup error: /home/surya/UnrealEngine/Engine/Plugins/UETorch/Binaries/Linux/../../../ScriptPlugin/Binaries/Linux/libUE4Editor-ScriptPlugin.so: undefined symbol: lua_newstate

The installation of UETorch went smoothly.

**Comment by adamlerer** [comment]
Did you install Lua and Torch before doing the Unreal installation? Did you install Lua 5.2? Can you check inside of Engine/Plugins/ScriptPlugin/Source/Lua to make sure the Lua libraries are inside there?
